/*
 * File: app/model/KisiModel.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('XYZPro.model.KisiModel', {
    extend: 'Ext.data.Model',
    alias: 'model.kisimodel',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'ad'
        },
        {
            type: 'string',
            name: 'soyad'
        },
        {
            type: 'string',
            name: 'dogumTarihi'
        },
        {
            type: 'int',
            name: 'cinsiyet'
        },
        {
            name: 'medeniDurum'
        },
        {
            type: 'int',
            name: 'unvanId'
        },
        {
            name: 'sicilNo'
        },
        {
            type: 'boolean',
            name: 'aktif'
        },
        {
            type: 'string',
            name: 'dogumYeri'
        },
        {
            type: 'string',
            name: 'uyruk'
        },
        {
            name: 'birimByBirimId'
        }
    ]
});