/*
 * File: app/view/ViewPersonelViewModel.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('XYZPro.view.ViewPersonelViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.viewpersonel',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    stores: {
        kisiModels: {
            model: 'XYZPro.model.KisiModel',
            proxy: {
                type: 'ajax',
                url: '/kisi/getKisiler.ajax',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }
    }

});