/*
 * File: app/view/WindowAdresEkleViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('XYZPro.view.WindowAdresEkleViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.windowadresekle',

    loadLookUp: function() {
        Ext.ComponentQuery.query('#cmbAdresTipi')[0].getStore().load({
          params:{
            'ustTanimId': 20
          }
        });
    },

    onCmbIlSelect: function(combo, record, eOpts) {
        var cmbIlce = Ext.ComponentQuery.query("#cmbIlce")[0];
        cmbIlce.clearValue();
        cmbIlce.getStore().load({
            params:{
                'ilId':record.data.il_id
            }
        });
    },

    onBtnAdresKaydetClick: function(button, e, eOpts) {
        var form = Ext.ComponentQuery.query('#adresFormPanel')[0];
        var kisiId = Ext.ComponentQuery.query('#kisiId')[0];
        var gridAdres = Ext.ComponentQuery.query('#gridAdresPanel')[0];

        Ext.Ajax.request({
            url: 'kisi/saveOrUpdateAdresBilgileri.ajax',

            params:
            {
                data: Ext.encode(form.getForm().getValues()),
                kisiId:kisiId.getValue()
            },

            success: function(response, opts) {
                gridAdres.getStore().load({
                    params:{
                        'kisiId':kisiId.getValue()
                    }
                });

            },

            failure: function(response, opts) {

            }

        });
    },

    onBtnAdresTemizleClick: function(button, e, eOpts) {
        var form = Ext.ComponentQuery.query('#adresFormPanel')[0];
        form.getForm().reset();
    },

    onWindowAfterRender: function(component, eOpts) {
        var window = this.getView();
        window.getController().loadLookUp();

        if(component.adresId!=""){
            Ext.Ajax.request
            ({
                url: '/kisi/getAdresBilgileriById.ajax',
                params:
                {
                    adresId:component.adresId
                },
                success: function(response, request) {
                    var formAdres = Ext.ComponentQuery.query("#adresFormPanel")[0];
                    var record=  Ext.data.Record.create(Ext.decode(response.responseText)[0]);
                    formAdres.loadRecord(record);
                },
                failure: {}


            }) ;
        }

    }

});
