/*
 * File: app/view/WindowsYoneticiAta.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('XYZPro.view.WindowsYoneticiAta', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowsyoneticiata',

    requires: [
        'XYZPro.view.WindowsYoneticiAtaViewModel',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'windowsyoneticiata'
    },
    height: 150,
    itemId: 'windowsYoneticiAta',
    width: 300,
    title: 'Yönetici Ata',

    items: [
        {
            xtype: 'form',
            itemId: 'viewYoneticiFormPanel',
            layout: 'form',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'combobox',
                    itemId: 'comboBirim',
                    fieldLabel: 'Birim',
                    displayField: 'birim_adi',
                    store: 'cmbBirimler',
                    valueField: 'id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    itemId: 'bToolbar',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            itemId: 'btnYoneticiAta',
                            text: 'Yönetici Ata'
                        }
                    ]
                }
            ]
        }
    ]

});