/*
 * File: app/view/WindowAdresEkle.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('XYZPro.view.WindowAdresEkle', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowadresekle',

    requires: [
        'XYZPro.view.WindowAdresEkleViewModel',
        'XYZPro.view.WindowAdresEkleViewController',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'windowadresekle',
    viewModel: {
        type: 'windowadresekle'
    },
    modal: true,
    height: 310,
    itemId: 'adresFormPanel',
    width: 300,
    title: 'Adres Ekle',

    items: [
        {
            xtype: 'form',
            itemId: 'adresFormPanel',
            layout: 'form',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'hiddenfield',
                    itemId: 'adresId',
                    fieldLabel: 'Label',
                    name: 'id'
                },
                {
                    xtype: 'combobox',
                    itemId: 'cmbAdresTipi',
                    fieldLabel: 'Adres Tipi',
                    name: 'adres_tipi',
                    allowBlank: false,
                    displayField: 'aciklama',
                    queryMode: 'local',
                    store: 'lookUpAdresTipi',
                    valueField: 'id'
                },
                {
                    xtype: 'textfield',
                    itemId: 'textDetay1',
                    fieldLabel: 'Adres Detay 1',
                    name: 'adres_detay1',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    itemId: 'textDetay2',
                    fieldLabel: 'Adres Detay 2',
                    name: 'adres_detay2'
                },
                {
                    xtype: 'textfield',
                    itemId: 'tctIcKapiNo',
                    fieldLabel: 'İç Kapı No',
                    name: 'ic_kapi_no',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    itemId: 'txtDisKapiNo',
                    fieldLabel: 'Dış Kapı No',
                    name: 'dis_kapi_no',
                    allowBlank: false
                },
                {
                    xtype: 'combobox',
                    itemId: 'cmbIl',
                    fieldLabel: 'İl',
                    name: 'il_id',
                    allowBlank: false,
                    displayField: 'aciklama',
                    store: 'cbmIller',
                    valueField: 'il_id',
                    listeners: {
                        select: 'onCmbIlSelect'
                    }
                },
                {
                    xtype: 'combobox',
                    itemId: 'cmbIlce',
                    fieldLabel: 'İlçe',
                    name: 'ilce_id',
                    allowBlank: false,
                    displayField: 'aciklama',
                    queryMode: 'local',
                    store: 'cbmIlceler',
                    valueField: 'ilce_id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    itemId: 'tbarAdres',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            itemId: 'btnAdresKaydet',
                            text: 'Kaydet',
                            listeners: {
                                click: 'onBtnAdresKaydetClick'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnAdresTemizle',
                            text: 'Temizle',
                            listeners: {
                                click: 'onBtnAdresTemizleClick'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'hiddenfield',
            itemId: 'kisiId',
            fieldLabel: 'Label',
            name: 'kisi_id'
        }
    ],
    listeners: {
        afterrender: 'onWindowAfterRender'
    }

});