/*
 * File: app/view/WindowYoneticiAta.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('XYZPro.view.WindowYoneticiAta', {
    extend: 'Ext.window.Window',
    alias: 'widget.windowyoneticiata',

    requires: [
        'XYZPro.view.WindowYoneticiAtaViewModel',
        'XYZPro.view.WindowYoneticiAtaViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'windowyoneticiata',
    viewModel: {
        type: 'windowyoneticiata'
    },
    modal: true,
    height: 150,
    itemId: 'windowYoneticiAta',
    width: 300,
    title: 'Yönetici Ata',

    items: [
        {
            xtype: 'form',
            itemId: 'viewYoneticiFormPanel',
            layout: 'form',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'combobox',
                    itemId: 'comboBirim',
                    fieldLabel: 'Birim',
                    name: 'birimId',
                    allowBlank: false,
                    displayField: 'birim_adi',
                    store: 'cmbBirimler',
                    valueField: 'id'
                },
                {
                    xtype: 'hiddenfield',
                    itemId: 'lblKisiId',
                    fieldLabel: 'Label',
                    name: 'kisiId'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    itemId: 'bToolbar',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            itemId: 'btnYoneticiAta',
                            text: 'Yönetici Ata',
                            listeners: {
                                click: 'onBtnYoneticiAtaClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});