/*
 * File: app/view/WindowYoneticiAtaViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('XYZPro.view.WindowYoneticiAtaViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.windowyoneticiata',

    onBtnYoneticiAtaClick: function(button, e, eOpts) {
        var form =Ext.ComponentQuery.query('#viewYoneticiFormPanel')[0];
        var windowYoneticiAta =Ext.ComponentQuery.query('#windowYoneticiAta')[0];

        Ext.Ajax.request({
            url: 'kisi/birimYoneticiAta.ajax',

            params:
            {
                data: Ext.encode(form.getForm().getValues())
            },

            success: function(response, opts) {
                Ext.toast("Yönetici Atama işlemi başarılı");
                windowYoneticiAta.close();
            },

            failure: function(response, opts) {

            }
        });
    }

});
